# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-15 13:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domain_name', models.CharField(max_length=40)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_spun', models.DateField(auto_now=True)),
                ('spun_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
            ],
        ),
    ]
