# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-15 13:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twister', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
