# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-15 13:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twister', '0002_domain_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='spun_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
